# Generated by Django 3.1.6 on 2021-02-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_num', models.CharField(default='U0000', max_length=12)),
                ('device_battery_left', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('device_status', models.IntegerField(choices=[(0, 'Used'), (1, 'Unused')], default=1)),
                ('left_right', models.IntegerField(choices=[(18, 'Left'), (81, 'Right'), (11, 'Unknown')], default=11)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_name', models.CharField(default='未命名场景', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='未命名', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unfilled', max_length=24)),
                ('trainee_num', models.CharField(default='0000', max_length=20)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('feet_size', models.CharField(default='99', max_length=4)),
                ('face_image_path', models.FilePathField(default='D:\\Bingo\\Projects\\2021_1_trainingSys\\src\\trainingSys\\media\\default.jpg')),
                ('lfeet_insole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linsole', to='trainingSys.insole')),
                ('rfeet_insole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rinsole', to='trainingSys.insole')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.team')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_order', models.JSONField(null=True)),
                ('training_date_start', models.DateTimeField(null=True)),
                ('training_date_end', models.DateTimeField(null=True)),
                ('situation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.situation')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.FilePathField(default='D:\\Bingo\\Projects\\2021_1_trainingSys\\src\\trainingSys\\media\\video\\default.avi')),
                ('pose_data_path', models.FilePathField(default='D:\\Bingo\\Projects\\2021_1_trainingSys\\src\\trainingSys\\media\\video\\default.json')),
                ('foot_data', models.JSONField(null=True)),
                ('video_type', models.IntegerField(choices=[(0, "team's"), (1, "individual's")], default=0)),
                ('video_fragment', models.JSONField(null=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.trainee')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_data', models.JSONField(null=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.trainee')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.training')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField(null=True)),
                ('report', models.TextField(default='尚未得出评估报告')),
                ('suggestion', models.TextField(default='尚未给出训练建议')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.trainee')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingSys.training')),
            ],
        ),
    ]
