# Generated by Django 3.1.6 on 2021-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insole',
            name='setting',
            field=models.JSONField(default='{}'),
        ),
    ]
