# Generated by Django 3.1.6 on 2021-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingSys', '0003_auto_20210220_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdata',
            old_name='foot_data',
            new_name='left_foot_data',
        ),
        migrations.AddField(
            model_name='assessment',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='training',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='right_foot_data',
            field=models.JSONField(null=True),
        ),
    ]
